/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as AuthenticatedDashboardRouteRouteImport } from "./pages/_authenticated/dashboard/route";
import { Route as AuthenticatedRouteRouteImport } from "./pages/_authenticated/route";
import { Route as AuthenticatedTasksTodoIdRouteRouteImport } from "./pages/_authenticated/tasks/$todoId/route";
import { Route as IndexRouteImport } from "./pages/index";
import { Route as LoginRouteRouteImport } from "./pages/login/route";

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: "/dashboard",
    path: "/dashboard",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedTasksTodoIdRouteRoute =
  AuthenticatedTasksTodoIdRouteRouteImport.update({
    id: "/tasks/$todoId",
    path: "/tasks/$todoId",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRouteRoute;
  "/dashboard": typeof AuthenticatedDashboardRouteRoute;
  "/tasks/$todoId": typeof AuthenticatedTasksTodoIdRouteRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRouteRoute;
  "/dashboard": typeof AuthenticatedDashboardRouteRoute;
  "/tasks/$todoId": typeof AuthenticatedTasksTodoIdRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/login": typeof LoginRouteRoute;
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRouteRoute;
  "/_authenticated/tasks/$todoId": typeof AuthenticatedTasksTodoIdRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/dashboard" | "/tasks/$todoId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/dashboard" | "/tasks/$todoId";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/dashboard"
    | "/_authenticated/tasks/$todoId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  LoginRouteRoute: typeof LoginRouteRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/tasks/$todoId": {
      id: "/_authenticated/tasks/$todoId";
      path: "/tasks/$todoId";
      fullPath: "/tasks/$todoId";
      preLoaderRoute: typeof AuthenticatedTasksTodoIdRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute;
  AuthenticatedTasksTodoIdRouteRoute: typeof AuthenticatedTasksTodoIdRouteRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedTasksTodoIdRouteRoute: AuthenticatedTasksTodoIdRouteRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
